import { PrismaClient, Stratum, SuccessionalStage, LifeCycle, CanopyShape, FoliageType, GrowthRate, RootSystem, BiomassProduction, PlantUse } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Create a test user first
  const testUser = await prisma.user.upsert({
    where: { email: 'test@syntropedia.org' },
    update: {},
    create: {
      name: 'Test User',
      email: 'test@syntropedia.org',
      role: 'ADMIN',
    },
  })

  console.log(`✅ Created test user: ${testUser.email}`)

  // Seed species data
  const speciesData = [
    {
      slug: 'jatoba-hymenaea-courbaril',
      scientificName: 'Hymenaea courbaril',
      genus: 'Hymenaea',
      species: 'courbaril',
      author: 'L.',
      commonNames: ['Jatobá', 'Jataí', 'Jutaí', 'Courbaril'],
      synonyms: ['Hymenaea resinifera'],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.EMERGENT,
      successionalStage: SuccessionalStage.CLIMAX,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 40.0,
      canopyWidthMeters: 15.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'América do Sul',
      globalBiome: 'Tropical',
      regionalBiome: ['Mata Atlântica', 'Amazônia', 'Cerrado'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAge: '10-15 years',
      uses: [PlantUse.HUMAN_FOOD, PlantUse.TIMBER, PlantUse.MEDICINAL, PlantUse.SHADE],
      propagationMethods: ['Seeds', 'Seedlings'],
      observations: 'Árvore de grande porte muito valorizada por sua madeira nobre e frutos comestíveis.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'banana-musa-paradisiaca',
      scientificName: 'Musa × paradisiaca',
      genus: 'Musa',
      species: 'paradisiaca',
      author: 'L.',
      commonNames: ['Banana', 'Bananeira', 'Pacoba'],
      synonyms: ['Musa sapientum'],
      botanicalFamily: 'Musaceae',
      stratum: Stratum.SUBCANOPY,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 6.0,
      canopyWidthMeters: 3.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Sudeste Asiático',
      globalBiome: 'Tropical',
      regionalBiome: ['Cultivada em toda região tropical'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAge: '9-12 months',
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.GROUND_COVER],
      propagationMethods: ['Rhizome division', 'Suckers'],
      observations: 'Planta de rápido crescimento, excelente para sistemas agroflorestais.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'palmito-jucara-euterpe-edulis',
      scientificName: 'Euterpe edulis',
      genus: 'Euterpe',
      species: 'edulis',
      author: 'Mart.',
      commonNames: ['Palmito-juçara', 'Juçara', 'Ripeira', 'Içara'],
      synonyms: [],
      botanicalFamily: 'Arecaceae',
      stratum: Stratum.CANOPY,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 15.0,
      canopyWidthMeters: 3.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Mata Atlântica',
      globalBiome: 'Tropical',
      regionalBiome: ['Mata Atlântica'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAge: '7-10 years',
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds'],
      observations: 'Espécie ameaçada de extinção. Importante para fauna. Frutos produzem açaí.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'cafe-coffea-arabica',
      scientificName: 'Coffea arabica',
      genus: 'Coffea',
      species: 'arabica',
      author: 'L.',
      commonNames: ['Café', 'Cafeeiro', 'Coffee'],
      synonyms: ['Coffea moka'],
      botanicalFamily: 'Rubiaceae',
      stratum: Stratum.UNDERSTORY,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 4.0,
      canopyWidthMeters: 2.5,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Etiópia',
      globalBiome: 'Tropical/Subtropical',
      regionalBiome: ['Cultivado em regiões montanhosas tropicais'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAge: '3-4 years',
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Cuttings'],
      observations: 'Planta de sombra, ideal para cultivo sob dossel de árvores maiores.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'acerola-malpighia-emarginata',
      scientificName: 'Malpighia emarginata',
      genus: 'Malpighia',
      species: 'emarginata',
      author: 'DC.',
      commonNames: ['Acerola', 'Cereja-das-antilhas', 'Barbados cherry'],
      synonyms: ['Malpighia glabra', 'Malpighia punicifolia'],
      botanicalFamily: 'Malpighiaceae',
      stratum: Stratum.UNDERSTORY,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 3.0,
      canopyWidthMeters: 2.5,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'América Central e Caribe',
      globalBiome: 'Tropical',
      regionalBiome: ['Cultivada em toda região tropical'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAge: '2-3 years',
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Cuttings', 'Grafting'],
      observations: 'Rica em vitamina C. Frutifica o ano todo em condições ideais.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'inga-edulis',
      scientificName: 'Inga edulis',
      genus: 'Inga',
      species: 'edulis',
      author: 'Mart.',
      commonNames: ['Ingá', 'Ingá-de-metro', 'Ingá-cipó', 'Ice cream bean'],
      synonyms: ['Inga jinicuil'],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.SUBCANOPY,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 10.0,
      canopyWidthMeters: 8.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'América do Sul',
      globalBiome: 'Tropical',
      regionalBiome: ['Amazônia', 'Mata Atlântica'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: true,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAge: '2-3 years',
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.SHADE, PlantUse.GROUND_COVER],
      propagationMethods: ['Seeds', 'Cuttings'],
      observations: 'Excelente fixador de nitrogênio. Crescimento rápido. Ótima para sombreamento.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'ipe-roxo-handroanthus-impetiginosus',
      scientificName: 'Handroanthus impetiginosus',
      genus: 'Handroanthus',
      species: 'impetiginosus',
      author: '(Mart. ex DC.) Mattos',
      commonNames: ['Ipê-roxo', 'Pau-d\'arco-roxo', 'Pink trumpet tree'],
      synonyms: ['Tabebuia impetiginosa', 'Tabebuia avellanedae'],
      botanicalFamily: 'Bignoniaceae',
      stratum: Stratum.CANOPY,
      successionalStage: SuccessionalStage.CLIMAX,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 30.0,
      canopyWidthMeters: 12.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'América do Sul',
      globalBiome: 'Tropical/Subtropical',
      regionalBiome: ['Cerrado', 'Mata Atlântica', 'Caatinga'],
      foliageType: FoliageType.DECIDUOUS,
      leafDropSeason: 'Inverno (para floração)',
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.TIMBER, PlantUse.MEDICINAL, PlantUse.ORNAMENTAL, PlantUse.HONEY],
      propagationMethods: ['Seeds'],
      observations: 'Árvore icônica com floração espetacular. Madeira nobre muito valorizada.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'mamao-carica-papaya',
      scientificName: 'Carica papaya',
      genus: 'Carica',
      species: 'papaya',
      author: 'L.',
      commonNames: ['Mamão', 'Papaia', 'Papaya', 'Pawpaw'],
      synonyms: [],
      botanicalFamily: 'Caricaceae',
      stratum: Stratum.SUBCANOPY,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      lifeCycleYears: '3-5 anos',
      heightMeters: 8.0,
      canopyWidthMeters: 2.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'América Central e México',
      globalBiome: 'Tropical',
      regionalBiome: ['Cultivado em toda região tropical'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAge: '8-12 months',
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Seeds'],
      observations: 'Crescimento rápido. Frutifica precocemente. Excelente para sistemas pioneiros.',
      status: 'PUBLISHED' as const,
    },
  ]

  console.log(`\n📦 Creating ${speciesData.length} species...`)

  for (const data of speciesData) {
    const species = await prisma.species.upsert({
      where: { slug: data.slug },
      update: {},
      create: {
        ...data,
        createdById: testUser.id,
      },
    })

    // Add a placeholder photo for each species
    // SVG placeholder - no external network call needed
    const photoUrl = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='600'%3E%3Crect width='800' height='600' fill='%234ade80'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='sans-serif' font-size='24' fill='white'%3E${encodeURIComponent(species.scientificName)}%3C/text%3E%3C/svg%3E`

    await prisma.photo.create({
      data: {
        url: photoUrl,
        caption: `${species.scientificName}`,
        tags: [species.genus || '', species.stratum],
        approved: true,
        primary: true,
        speciesId: species.id,
        uploadById: testUser.id,
      },
    })

    console.log(`  ✅ ${species.scientificName} (${species.slug})`)
  }

  console.log('\n🎉 Seed completed successfully!')
  console.log(`\n📊 Summary:`)
  console.log(`   Users: ${await prisma.user.count()}`)
  console.log(`   Species: ${await prisma.species.count()}`)
  console.log(`   Photos: ${await prisma.photo.count()}`)
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
