import { PrismaClient, Stratum, SuccessionalStage, LifeCycle, CanopyShape, FoliageType, GrowthRate, RootSystem, BiomassProduction, PlantUse, UserRole, BadgeCategory } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Create users with gamification data
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@syntropedia.org' },
    update: { xp: 5000, level: 7, title: 'Horticulturist' },
    create: {
      name: 'Admin User',
      email: 'admin@syntropedia.org',
      role: UserRole.ADMIN,
      xp: 5000,
      level: 7,
      title: 'Horticulturist',
    },
  })

  const user1 = await prisma.user.upsert({
    where: { email: 'maria.silva@syntropedia.org' },
    update: { xp: 1200, level: 4, title: 'Green Thumb' },
    create: {
      name: 'Maria Silva',
      email: 'maria.silva@syntropedia.org',
      role: UserRole.USER,
      xp: 1200,
      level: 4,
      title: 'Green Thumb',
    },
  })

  const user2 = await prisma.user.upsert({
    where: { email: 'joao.santos@syntropedia.org' },
    update: { xp: 450, level: 3, title: 'Sapling' },
    create: {
      name: 'João Santos',
      email: 'joao.santos@syntropedia.org',
      role: UserRole.USER,
      xp: 450,
      level: 3,
      title: 'Sapling',
    },
  })

  // Create reviewers with gamification data
  const reviewer1 = await prisma.user.upsert({
    where: { email: 'dr.botanica@syntropedia.org' },
    update: { xp: 8500, level: 8, title: 'Botanist' },
    create: {
      name: 'Dr. Ana Botânica',
      email: 'dr.botanica@syntropedia.org',
      role: UserRole.REVIEWER,
      xp: 8500,
      level: 8,
      title: 'Botanist',
    },
  })

  const reviewer2 = await prisma.user.upsert({
    where: { email: 'prof.agroforestry@syntropedia.org' },
    update: { xp: 3200, level: 6, title: 'Gardener' },
    create: {
      name: 'Prof. Carlos Agroflorestas',
      email: 'prof.agroforestry@syntropedia.org',
      role: UserRole.REVIEWER,
      xp: 3200,
      level: 6,
      title: 'Gardener',
    },
  })

  const reviewer3 = await prisma.user.upsert({
    where: { email: 'researcher.ecology@syntropedia.org' },
    update: { xp: 2100, level: 5, title: 'Cultivator' },
    create: {
      name: 'Dra. Fernanda Ecologia',
      email: 'researcher.ecology@syntropedia.org',
      role: UserRole.REVIEWER,
      xp: 2100,
      level: 5,
      title: 'Cultivator',
    },
  })

  console.log(`✅ Created users:`)
  console.log(`   Admin: ${adminUser.email}`)
  console.log(`   Users: ${user1.email}, ${user2.email}`)
  console.log(`   Reviewers: ${reviewer1.email}, ${reviewer2.email}, ${reviewer3.email}`)

  const allUsers = [adminUser, user1, user2, reviewer1, reviewer2, reviewer3]

  // Seed species data - 50+ species
  const speciesData = [
    // EMERGENT STRATUM
    {
      slug: 'jatoba-hymenaea-courbaril',
      scientificName: 'Hymenaea courbaril',
      genus: 'Hymenaea',
      species: 'courbaril',
      author: 'L.',
      commonNames: ['Jatobá', 'Jataí', 'Jutaí', 'Courbaril'],
      synonyms: ['Hymenaea resinifera'],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.EMERGENT,
      successionalStage: SuccessionalStage.CLIMAX,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 40.0,
      canopyWidthMeters: 15.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['ATLANTIC_FOREST', 'AMAZON', 'CERRADO'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 10, fruitingAgeEnd: 15,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.TIMBER, PlantUse.MEDICINAL, PlantUse.SHADE],
      propagationMethods: ['Seeds', 'Seedlings'],
      germinationDaysMin: 30, germinationDaysMax: 90,
      observations: 'Large tree valued for its noble wood and edible fruits.',
      status: 'IN_REVIEW' as const,
    },
    {
      slug: 'brazil-nut-bertholletia-excelsa',
      scientificName: 'Bertholletia excelsa',
      genus: 'Bertholletia',
      species: 'excelsa',
      author: 'Bonpl.',
      commonNames: ['Brazil Nut', 'Castanha-do-Pará', 'Castanha-do-Brasil'],
      synonyms: [],
      botanicalFamily: 'Lecythidaceae',
      stratum: Stratum.EMERGENT,
      successionalStage: SuccessionalStage.CLIMAX,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 50.0,
      canopyWidthMeters: 20.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 12, fruitingAgeEnd: 15,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.TIMBER, PlantUse.OIL],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 120, germinationDaysMax: 365,
      observations: 'One of the tallest trees in the Amazon. Requires specific pollinators.',
      status: 'IN_REVIEW' as const,
    },
    {
      slug: 'kapok-ceiba-pentandra',
      scientificName: 'Ceiba pentandra',
      genus: 'Ceiba',
      species: 'pentandra',
      author: '(L.) Gaertn.',
      commonNames: ['Kapok', 'Sumaúma', 'Silk-cotton tree'],
      synonyms: ['Bombax pentandrum'],
      botanicalFamily: 'Malvaceae',
      stratum: Stratum.EMERGENT,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 60.0,
      canopyWidthMeters: 25.0,
      canopyShape: CanopyShape.UMBRELLA,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON', 'ATLANTIC_FOREST'],
      foliageType: FoliageType.DECIDUOUS,
      leafDropSeason: 'Dry season',
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: false,
      uses: [PlantUse.FIBER, PlantUse.TIMBER, PlantUse.SHADE],
      propagationMethods: ['Seeds', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Sacred tree in many cultures. Fiber used for stuffing.',
      status: 'IN_REVIEW' as const,
    },
    {
      slug: 'mahogany-swietenia-macrophylla',
      scientificName: 'Swietenia macrophylla',
      genus: 'Swietenia',
      species: 'macrophylla',
      author: 'King',
      commonNames: ['Mahogany', 'Mogno', 'Caoba'],
      synonyms: [],
      botanicalFamily: 'Meliaceae',
      stratum: Stratum.EMERGENT,
      successionalStage: SuccessionalStage.CLIMAX,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 45.0,
      canopyWidthMeters: 18.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON', 'ATLANTIC_FOREST'],
      foliageType: FoliageType.SEMI_DECIDUOUS,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: false,
      uses: [PlantUse.TIMBER, PlantUse.SHADE],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Premium timber species. CITES protected.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'african-mahogany-khaya-senegalensis',
      scientificName: 'Khaya senegalensis',
      genus: 'Khaya',
      species: 'senegalensis',
      author: '(Desr.) A.Juss.',
      commonNames: ['African Mahogany', 'Mogno-africano', 'Dry Zone Mahogany'],
      synonyms: [],
      botanicalFamily: 'Meliaceae',
      stratum: Stratum.EMERGENT,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 35.0,
      canopyWidthMeters: 15.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Ethiopia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.SEMI_DECIDUOUS,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: false,
      uses: [PlantUse.TIMBER, PlantUse.MEDICINAL, PlantUse.SHADE],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Resistant to mahogany shoot borer. Alternative to native mahogany.',
      status: 'PUBLISHED' as const,
    },

    // CANOPY STRATUM
    {
      slug: 'palmito-jucara-euterpe-edulis',
      scientificName: 'Euterpe edulis',
      genus: 'Euterpe',
      species: 'edulis',
      author: 'Mart.',
      commonNames: ['Palmito-juçara', 'Juçara', 'Ripeira', 'Içara'],
      synonyms: [],
      botanicalFamily: 'Arecaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 15.0,
      canopyWidthMeters: 3.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['ATLANTIC_FOREST'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 7, fruitingAgeEnd: 10,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Endangered species. Important for fauna. Fruits produce açaí.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'ipe-roxo-handroanthus-impetiginosus',
      scientificName: 'Handroanthus impetiginosus',
      genus: 'Handroanthus',
      species: 'impetiginosus',
      author: '(Mart. ex DC.) Mattos',
      commonNames: ['Ipê-roxo', 'Pau-d\'arco-roxo', 'Pink trumpet tree'],
      synonyms: ['Tabebuia impetiginosa', 'Tabebuia avellanedae'],
      botanicalFamily: 'Bignoniaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.CLIMAX,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 30.0,
      canopyWidthMeters: 12.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['CERRADO', 'ATLANTIC_FOREST', 'CAATINGA'],
      foliageType: FoliageType.DECIDUOUS,
      leafDropSeason: 'Winter (for flowering)',
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.TIMBER, PlantUse.MEDICINAL, PlantUse.ORNAMENTAL, PlantUse.HONEY],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Iconic tree with spectacular flowering. Noble wood highly valued.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'ipe-amarelo-handroanthus-albus',
      scientificName: 'Handroanthus albus',
      genus: 'Handroanthus',
      species: 'albus',
      author: '(Cham.) Mattos',
      commonNames: ['Ipê-amarelo', 'Ipê-branco', 'Yellow trumpet tree'],
      synonyms: ['Tabebuia alba'],
      botanicalFamily: 'Bignoniaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 25.0,
      canopyWidthMeters: 10.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'SUBTROPICAL_FOREST',
      regionalBiome: ['ATLANTIC_FOREST', 'ATLANTIC_FOREST'],
      foliageType: FoliageType.DECIDUOUS,
      leafDropSeason: 'Winter',
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.TIMBER, PlantUse.ORNAMENTAL, PlantUse.HONEY],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Brazil national tree. Beautiful yellow flowering.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'avocado-persea-americana',
      scientificName: 'Persea americana',
      genus: 'Persea',
      species: 'americana',
      author: 'Mill.',
      commonNames: ['Avocado', 'Abacate', 'Aguacate', 'Palta'],
      synonyms: ['Persea gratissima'],
      botanicalFamily: 'Lauraceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 20.0,
      canopyWidthMeters: 12.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 4, fruitingAgeEnd: 6,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.OIL, PlantUse.SHADE],
      propagationMethods: ['Seeds', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'High nutritional value fruit. Many cultivated varieties.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'mango-mangifera-indica',
      scientificName: 'Mangifera indica',
      genus: 'Mangifera',
      species: 'indica',
      author: 'L.',
      commonNames: ['Mango', 'Manga', 'Mangueira'],
      synonyms: [],
      botanicalFamily: 'Anacardiaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 25.0,
      canopyWidthMeters: 15.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 5, fruitingAgeEnd: 8,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.SHADE, PlantUse.TIMBER],
      propagationMethods: ['Seeds', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'King of fruits. Hundreds of cultivars available.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'jackfruit-artocarpus-heterophyllus',
      scientificName: 'Artocarpus heterophyllus',
      genus: 'Artocarpus',
      species: 'heterophyllus',
      author: 'Lam.',
      commonNames: ['Jackfruit', 'Jaca', 'Nangka'],
      synonyms: ['Artocarpus integrifolius'],
      botanicalFamily: 'Moraceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 20.0,
      canopyWidthMeters: 12.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.TIMBER, PlantUse.SHADE, PlantUse.ANIMAL_FOOD],
      propagationMethods: ['Seeds', 'Grafting', 'Air layering'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Largest tree-borne fruit. Seeds also edible.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'breadfruit-artocarpus-altilis',
      scientificName: 'Artocarpus altilis',
      genus: 'Artocarpus',
      species: 'altilis',
      author: '(Parkinson) Fosberg',
      commonNames: ['Breadfruit', 'Fruta-pão', 'Árbol del pan'],
      synonyms: ['Artocarpus communis'],
      botanicalFamily: 'Moraceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 20.0,
      canopyWidthMeters: 12.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.TIMBER, PlantUse.SHADE],
      propagationMethods: ['Root cuttings', 'Air layering'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Staple food in Pacific islands. High carbohydrate content.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'acai-euterpe-oleracea',
      scientificName: 'Euterpe oleracea',
      genus: 'Euterpe',
      species: 'oleracea',
      author: 'Mart.',
      commonNames: ['Açaí', 'Açaizeiro', 'Acai palm'],
      synonyms: [],
      botanicalFamily: 'Arecaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 20.0,
      canopyWidthMeters: 3.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON', 'PANTANAL'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 4, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 30, germinationDaysMax: 90,
      observations: 'Clumping palm. Superfood with high antioxidants. Tolerates flooding.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'coconut-cocos-nucifera',
      scientificName: 'Cocos nucifera',
      genus: 'Cocos',
      species: 'nucifera',
      author: 'L.',
      commonNames: ['Coconut', 'Coco', 'Coqueiro'],
      synonyms: [],
      botanicalFamily: 'Arecaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 25.0,
      canopyWidthMeters: 8.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 5, fruitingAgeEnd: 7,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.OIL, PlantUse.FIBER, PlantUse.TIMBER, PlantUse.HANDICRAFT],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 90, germinationDaysMax: 180,
      observations: 'Tree of life. Every part is useful. Salt tolerant.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'peach-palm-bactris-gasipaes',
      scientificName: 'Bactris gasipaes',
      genus: 'Bactris',
      species: 'gasipaes',
      author: 'Kunth',
      commonNames: ['Peach Palm', 'Pupunha', 'Pejibaye', 'Chontaduro'],
      synonyms: [],
      botanicalFamily: 'Arecaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 20.0,
      canopyWidthMeters: 4.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON', 'CERRADO'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 4,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD],
      propagationMethods: ['Seeds', 'Suckers'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Clumping palm. Fruits high in beta-carotene. Hearts of palm source.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'neem-azadirachta-indica',
      scientificName: 'Azadirachta indica',
      genus: 'Azadirachta',
      species: 'indica',
      author: 'A.Juss.',
      commonNames: ['Neem', 'Nim', 'Margosa'],
      synonyms: ['Melia azadirachta'],
      botanicalFamily: 'Meliaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 20.0,
      canopyWidthMeters: 12.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['CAATINGA'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: false,
      uses: [PlantUse.MEDICINAL, PlantUse.TIMBER, PlantUse.SHADE, PlantUse.FIREWOOD],
      propagationMethods: ['Seeds', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Natural pesticide. Drought tolerant. Many medicinal uses.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'moringa-moringa-oleifera',
      scientificName: 'Moringa oleifera',
      genus: 'Moringa',
      species: 'oleifera',
      author: 'Lam.',
      commonNames: ['Moringa', 'Drumstick tree', 'Horseradish tree'],
      synonyms: ['Moringa pterygosperma'],
      botanicalFamily: 'Moringaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 12.0,
      canopyWidthMeters: 8.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.DECIDUOUS,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 2,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.MEDICINAL, PlantUse.OIL],
      propagationMethods: ['Seeds', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Superfood. Leaves extremely nutritious. Drought tolerant.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'tamarind-tamarindus-indica',
      scientificName: 'Tamarindus indica',
      genus: 'Tamarindus',
      species: 'indica',
      author: 'L.',
      commonNames: ['Tamarind', 'Tamarindo', 'Tamarineiro'],
      synonyms: [],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.HIGH,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 25.0,
      canopyWidthMeters: 15.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Ethiopia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 6, fruitingAgeEnd: 8,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.TIMBER, PlantUse.SHADE],
      propagationMethods: ['Seeds', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Long-lived tree. Pods used in cooking and medicine.',
      status: 'PUBLISHED' as const,
    },

    // SUBCANOPY STRATUM
    {
      slug: 'banana-musa-paradisiaca',
      scientificName: 'Musa × paradisiaca',
      genus: 'Musa',
      species: 'paradisiaca',
      author: 'L.',
      commonNames: ['Banana', 'Bananeira', 'Pacoba'],
      synonyms: ['Musa sapientum'],
      botanicalFamily: 'Musaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 6.0,
      canopyWidthMeters: 3.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 1,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.GROUND_COVER],
      propagationMethods: ['Rhizome division', 'Suckers'],
      germinationDaysMin: 14, germinationDaysMax: 21,
      observations: 'Fast growing. Excellent for agroforestry systems.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'inga-edulis',
      scientificName: 'Inga edulis',
      genus: 'Inga',
      species: 'edulis',
      author: 'Mart.',
      commonNames: ['Ingá', 'Ingá-de-metro', 'Ingá-cipó', 'Ice cream bean'],
      synonyms: ['Inga jinicuil'],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 10.0,
      canopyWidthMeters: 8.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON', 'ATLANTIC_FOREST'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: true,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 2, fruitingAgeEnd: 3,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.SHADE, PlantUse.GROUND_COVER],
      propagationMethods: ['Seeds', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Excellent nitrogen fixer. Fast growing. Great for shading.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'mamao-carica-papaya',
      scientificName: 'Carica papaya',
      genus: 'Carica',
      species: 'papaya',
      author: 'L.',
      commonNames: ['Papaya', 'Mamão', 'Pawpaw'],
      synonyms: [],
      botanicalFamily: 'Caricaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      lifeCycleYearsStart: 3, lifeCycleYearsEnd: 5,
      heightMeters: 8.0,
      canopyWidthMeters: 2.0,
      canopyShape: CanopyShape.PALM,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 1,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 10, germinationDaysMax: 21,
      observations: 'Fast growing. Fruits early. Excellent for pioneer systems.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'citrus-orange-citrus-sinensis',
      scientificName: 'Citrus sinensis',
      genus: 'Citrus',
      species: 'sinensis',
      author: '(L.) Osbeck',
      commonNames: ['Orange', 'Laranja', 'Naranja'],
      synonyms: ['Citrus aurantium sinensis'],
      botanicalFamily: 'Rutaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 8.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['CERRADO'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.ORNAMENTAL],
      propagationMethods: ['Grafting', 'Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Most popular citrus fruit. Many cultivars available.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'citrus-lemon-citrus-limon',
      scientificName: 'Citrus limon',
      genus: 'Citrus',
      species: 'limon',
      author: '(L.) Osbeck',
      commonNames: ['Lemon', 'Limão-siciliano', 'Limón'],
      synonyms: [],
      botanicalFamily: 'Rutaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 6.0,
      canopyWidthMeters: 5.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'India',
      globalBiome: 'SUBTROPICAL_FOREST',
      regionalBiome: ['CERRADO'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 4,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Grafting', 'Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'High vitamin C content. Used in cooking and cleaning.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'guava-psidium-guajava',
      scientificName: 'Psidium guajava',
      genus: 'Psidium',
      species: 'guajava',
      author: 'L.',
      commonNames: ['Guava', 'Goiaba', 'Guayaba'],
      synonyms: [],
      botanicalFamily: 'Myrtaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 8.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 2, fruitingAgeEnd: 4,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.TIMBER],
      propagationMethods: ['Seeds', 'Cuttings', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Rich in vitamin C. Fruits year-round in tropics.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'jabuticaba-plinia-cauliflora',
      scientificName: 'Plinia cauliflora',
      genus: 'Plinia',
      species: 'cauliflora',
      author: '(Mart.) Kausel',
      commonNames: ['Jabuticaba', 'Jaboticaba', 'Brazilian grape tree'],
      synonyms: ['Myrciaria cauliflora'],
      botanicalFamily: 'Myrtaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 10.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['ATLANTIC_FOREST', 'CERRADO'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 8, fruitingAgeEnd: 15,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Cauliflorous fruiting. Fruits grow directly on trunk.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'soursop-annona-muricata',
      scientificName: 'Annona muricata',
      genus: 'Annona',
      species: 'muricata',
      author: 'L.',
      commonNames: ['Soursop', 'Graviola', 'Guanábana'],
      synonyms: [],
      botanicalFamily: 'Annonaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 8.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.CONICAL,
      originCenter: 'Cuba',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Seeds', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Delicious fruit. Used in juices and ice creams.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'cacao-theobroma-cacao',
      scientificName: 'Theobroma cacao',
      genus: 'Theobroma',
      species: 'cacao',
      author: 'L.',
      commonNames: ['Cacao', 'Cacau', 'Cocoa'],
      synonyms: [],
      botanicalFamily: 'Malvaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 8.0,
      canopyWidthMeters: 5.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON', 'ATLANTIC_FOREST'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD],
      propagationMethods: ['Seeds', 'Grafting', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Shade-loving. Source of chocolate. Cauliflorous.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'cupuacu-theobroma-grandiflorum',
      scientificName: 'Theobroma grandiflorum',
      genus: 'Theobroma',
      species: 'grandiflorum',
      author: '(Willd. ex Spreng.) K.Schum.',
      commonNames: ['Cupuaçu', 'Cupuassu', 'Copoasu'],
      synonyms: [],
      botanicalFamily: 'Malvaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 10.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 4, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD],
      propagationMethods: ['Seeds', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Related to cacao. Aromatic pulp used in juices and desserts.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'starfruit-averrhoa-carambola',
      scientificName: 'Averrhoa carambola',
      genus: 'Averrhoa',
      species: 'carambola',
      author: 'L.',
      commonNames: ['Starfruit', 'Carambola', 'Five-finger'],
      synonyms: [],
      botanicalFamily: 'Oxalidaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 8.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 4, fruitingAgeEnd: 5,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Star-shaped fruit cross-section. Fruits year-round.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'lychee-litchi-chinensis',
      scientificName: 'Litchi chinensis',
      genus: 'Litchi',
      species: 'chinensis',
      author: 'Sonn.',
      commonNames: ['Lychee', 'Lichia', 'Litchi'],
      synonyms: [],
      botanicalFamily: 'Sapindaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 12.0,
      canopyWidthMeters: 8.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'China',
      globalBiome: 'SUBTROPICAL_FOREST',
      regionalBiome: ['ATLANTIC_FOREST'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 5, fruitingAgeEnd: 10,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ORNAMENTAL, PlantUse.HONEY],
      propagationMethods: ['Air layering', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Prized fruit. Needs cool period for flowering.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'rambutan-nephelium-lappaceum',
      scientificName: 'Nephelium lappaceum',
      genus: 'Nephelium',
      species: 'lappaceum',
      author: 'L.',
      commonNames: ['Rambutan', 'Rambutão', 'Hairy fruit'],
      synonyms: [],
      botanicalFamily: 'Sapindaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 12.0,
      canopyWidthMeters: 8.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 5, fruitingAgeEnd: 6,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Grafting', 'Air layering'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Related to lychee. Hairy red fruit.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'gliricidia-gliricidia-sepium',
      scientificName: 'Gliricidia sepium',
      genus: 'Gliricidia',
      species: 'sepium',
      author: '(Jacq.) Kunth ex Walp.',
      commonNames: ['Gliricidia', 'Madre de cacao', 'Quick stick'],
      synonyms: [],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 10.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.DECIDUOUS,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: true,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.ANIMAL_FOOD, PlantUse.SHADE, PlantUse.FIREWOOD, PlantUse.HEDGING],
      propagationMethods: ['Cuttings', 'Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Excellent nitrogen fixer. Living fence. Forage for livestock.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'leucaena-leucaena-leucocephala',
      scientificName: 'Leucaena leucocephala',
      genus: 'Leucaena',
      species: 'leucocephala',
      author: '(Lam.) de Wit',
      commonNames: ['Leucaena', 'Lead tree', 'Leucena'],
      synonyms: ['Leucaena glauca'],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 12.0,
      canopyWidthMeters: 6.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: true,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.ANIMAL_FOOD, PlantUse.SHADE, PlantUse.FIREWOOD, PlantUse.TIMBER],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'High-protein forage. Excellent nitrogen fixer. Can be invasive.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'mulberry-morus-nigra',
      scientificName: 'Morus nigra',
      genus: 'Morus',
      species: 'nigra',
      author: 'L.',
      commonNames: ['Black Mulberry', 'Amora-preta', 'Morera negra'],
      synonyms: [],
      botanicalFamily: 'Moraceae',
      stratum: Stratum.MEDIUM,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 10.0,
      canopyWidthMeters: 8.0,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Iran',
      globalBiome: 'TEMPERATE_FOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.DECIDUOUS,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 2, fruitingAgeEnd: 3,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Cuttings', 'Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Delicious fruit. Leaves feed silkworms. Fast establishment.',
      status: 'PUBLISHED' as const,
    },

    // UNDERSTORY STRATUM
    {
      slug: 'cafe-coffea-arabica',
      scientificName: 'Coffea arabica',
      genus: 'Coffea',
      species: 'arabica',
      author: 'L.',
      commonNames: ['Coffee', 'Café', 'Cafeeiro'],
      synonyms: ['Coffea moka'],
      botanicalFamily: 'Rubiaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.EARLY_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 4.0,
      canopyWidthMeters: 2.5,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Ethiopia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['ATLANTIC_FOREST'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 4,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Shade plant. Ideal for cultivation under tree canopy.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'acerola-malpighia-emarginata',
      scientificName: 'Malpighia emarginata',
      genus: 'Malpighia',
      species: 'emarginata',
      author: 'DC.',
      commonNames: ['Acerola', 'Barbados cherry', 'West Indian cherry'],
      synonyms: ['Malpighia glabra', 'Malpighia punicifolia'],
      botanicalFamily: 'Malpighiaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 3.0,
      canopyWidthMeters: 2.5,
      canopyShape: CanopyShape.ROUNDED,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 2, fruitingAgeEnd: 3,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Cuttings', 'Grafting'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Rich in vitamin C. Fruits year-round in ideal conditions.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'yerba-mate-ilex-paraguariensis',
      scientificName: 'Ilex paraguariensis',
      genus: 'Ilex',
      species: 'paraguariensis',
      author: 'A.St.-Hil.',
      commonNames: ['Yerba Mate', 'Erva-mate', 'Chimarrão'],
      synonyms: [],
      botanicalFamily: 'Aquifoliaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 8.0,
      canopyWidthMeters: 4.0,
      canopyShape: CanopyShape.CONICAL,
      originCenter: 'Brazil',
      globalBiome: 'SUBTROPICAL_FOREST',
      regionalBiome: ['ATLANTIC_FOREST', 'ATLANTIC_FOREST'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.SLOW,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: false,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Seeds', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Traditional beverage. Shade-tolerant. Native forest understory.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'hibiscus-hibiscus-sabdariffa',
      scientificName: 'Hibiscus sabdariffa',
      genus: 'Hibiscus',
      species: 'sabdariffa',
      author: 'L.',
      commonNames: ['Roselle', 'Hibiscus', 'Jamaica', 'Vinagreira'],
      synonyms: [],
      botanicalFamily: 'Malvaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.ANNUAL,
      heightMeters: 2.5,
      canopyWidthMeters: 1.5,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Ethiopia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.DECIDUOUS,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.FIBER],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Calyces used for tea and food coloring. Annual replanting.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'pigeon-pea-cajanus-cajan',
      scientificName: 'Cajanus cajan',
      genus: 'Cajanus',
      species: 'cajan',
      author: '(L.) Huth',
      commonNames: ['Pigeon Pea', 'Feijão-guandu', 'Guandu', 'Gandul'],
      synonyms: ['Cajanus indicus'],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      lifeCycleYearsStart: 3, lifeCycleYearsEnd: 5,
      heightMeters: 4.0,
      canopyWidthMeters: 2.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.SEMI_EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: true,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 1,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.FIREWOOD],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Nitrogen fixer. Drought tolerant. Deep rooting for soil improvement.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'cardamom-elettaria-cardamomum',
      scientificName: 'Elettaria cardamomum',
      genus: 'Elettaria',
      species: 'cardamomum',
      author: '(L.) Maton',
      commonNames: ['Cardamom', 'Cardamomo', 'Queen of Spices'],
      synonyms: [],
      botanicalFamily: 'Zingiberaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 4.0,
      canopyWidthMeters: 2.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['ATLANTIC_FOREST'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 4,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Seeds', 'Rhizome division'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Expensive spice. Shade-loving. Requires humid conditions.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'vanilla-vanilla-planifolia',
      scientificName: 'Vanilla planifolia',
      genus: 'Vanilla',
      species: 'planifolia',
      author: 'Jacks. ex Andrews',
      commonNames: ['Vanilla', 'Baunilha', 'Vainilla'],
      synonyms: ['Vanilla fragrans'],
      botanicalFamily: 'Orchidaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 10.0,
      canopyWidthMeters: 1.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.ADVENTITIOUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.LOW,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 4,
      uses: [PlantUse.HUMAN_FOOD],
      propagationMethods: ['Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Climbing orchid. Hand pollination required. Valuable spice.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'black-pepper-piper-nigrum',
      scientificName: 'Piper nigrum',
      genus: 'Piper',
      species: 'nigrum',
      author: 'L.',
      commonNames: ['Black Pepper', 'Pimenta-do-reino', 'Pimienta negra'],
      synonyms: [],
      botanicalFamily: 'Piperaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.LATE_SECONDARY,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 4.0,
      canopyWidthMeters: 1.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.ADVENTITIOUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.LOW,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 3, fruitingAgeEnd: 4,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Climbing vine. King of spices. Needs support tree.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'pitaya-hylocereus-undatus',
      scientificName: 'Hylocereus undatus',
      genus: 'Hylocereus',
      species: 'undatus',
      author: '(Haw.) Britton & Rose',
      commonNames: ['Dragon Fruit', 'Pitaya', 'Pitahaya'],
      synonyms: [],
      botanicalFamily: 'Cactaceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 5.0,
      canopyWidthMeters: 3.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Mexico',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.ADVENTITIOUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 2,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ORNAMENTAL],
      propagationMethods: ['Cuttings', 'Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Climbing cactus. Needs support. Night-blooming flowers.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'passion-fruit-passiflora-edulis',
      scientificName: 'Passiflora edulis',
      genus: 'Passiflora',
      species: 'edulis',
      author: 'Sims',
      commonNames: ['Passion Fruit', 'Maracujá', 'Maracuyá'],
      synonyms: [],
      botanicalFamily: 'Passifloraceae',
      stratum: Stratum.LOW,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      lifeCycleYearsStart: 5, lifeCycleYearsEnd: 7,
      heightMeters: 6.0,
      canopyWidthMeters: 4.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 2,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.ORNAMENTAL],
      propagationMethods: ['Seeds', 'Cuttings'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Climbing vine. Spectacular flowers. Fast fruiting.',
      status: 'PUBLISHED' as const,
    },

    // GROUND COVER STRATUM
    {
      slug: 'pineapple-ananas-comosus',
      scientificName: 'Ananas comosus',
      genus: 'Ananas',
      species: 'comosus',
      author: '(L.) Merr.',
      commonNames: ['Pineapple', 'Abacaxi', 'Piña'],
      synonyms: ['Ananas sativus'],
      botanicalFamily: 'Bromeliaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 1.5,
      canopyWidthMeters: 1.5,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 1,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.FIBER],
      propagationMethods: ['Crowns', 'Slips', 'Suckers'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Excellent ground cover between rows. Drought tolerant.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'ginger-zingiber-officinale',
      scientificName: 'Zingiber officinale',
      genus: 'Zingiber',
      species: 'officinale',
      author: 'Roscoe',
      commonNames: ['Ginger', 'Gengibre', 'Jengibre'],
      synonyms: [],
      botanicalFamily: 'Zingiberaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 1.0,
      canopyWidthMeters: 0.5,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.DECIDUOUS,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Rhizome division'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Shade-tolerant. Harvested 8-10 months after planting.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'turmeric-curcuma-longa',
      scientificName: 'Curcuma longa',
      genus: 'Curcuma',
      species: 'longa',
      author: 'L.',
      commonNames: ['Turmeric', 'Açafrão-da-terra', 'Cúrcuma'],
      synonyms: ['Curcuma domestica'],
      botanicalFamily: 'Zingiberaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 1.0,
      canopyWidthMeters: 0.5,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.DECIDUOUS,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL],
      propagationMethods: ['Rhizome division'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Anti-inflammatory properties. Used in cooking and medicine.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'taro-colocasia-esculenta',
      scientificName: 'Colocasia esculenta',
      genus: 'Colocasia',
      species: 'esculenta',
      author: '(L.) Schott',
      commonNames: ['Taro', 'Inhame', 'Taioba', 'Dasheen'],
      synonyms: [],
      botanicalFamily: 'Araceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 1.5,
      canopyWidthMeters: 1.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Indonesia',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TUBEROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD],
      propagationMethods: ['Corm division'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Tolerates wet conditions. Corms and leaves edible when cooked.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'sweet-potato-ipomoea-batatas',
      scientificName: 'Ipomoea batatas',
      genus: 'Ipomoea',
      species: 'batatas',
      author: '(L.) Lam.',
      commonNames: ['Sweet Potato', 'Batata-doce', 'Camote'],
      synonyms: [],
      botanicalFamily: 'Convolvulaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 0.5,
      canopyWidthMeters: 3.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.VERY_FAST,
      rootSystem: RootSystem.TUBEROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.VERY_HIGH,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD],
      propagationMethods: ['Vine cuttings', 'Slips'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Excellent ground cover. Tubers and leaves edible.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'cassava-manihot-esculenta',
      scientificName: 'Manihot esculenta',
      genus: 'Manihot',
      species: 'esculenta',
      author: 'Crantz',
      commonNames: ['Cassava', 'Mandioca', 'Yuca', 'Tapioca'],
      synonyms: ['Manihot utilissima'],
      botanicalFamily: 'Euphorbiaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 3.0,
      canopyWidthMeters: 2.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.SEMI_DECIDUOUS,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TUBEROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: true,
      edibleFruit: false,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD],
      propagationMethods: ['Stem cuttings'],
      germinationDaysMin: null, germinationDaysMax: null,
      observations: 'Staple food for millions. Drought tolerant. Tuberous roots.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'lemongrass-cymbopogon-citratus',
      scientificName: 'Cymbopogon citratus',
      genus: 'Cymbopogon',
      species: 'citratus',
      author: '(DC.) Stapf',
      commonNames: ['Lemongrass', 'Capim-limão', 'Hierba limón'],
      synonyms: [],
      botanicalFamily: 'Poaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 1.5,
      canopyWidthMeters: 1.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'India',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.HIGH,
      hasFruit: false,
      edibleFruit: false,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.MEDICINAL, PlantUse.OIL],
      propagationMethods: ['Division'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Aromatic grass. Insect repellent. Used in teas and cooking.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'peanut-arachis-hypogaea',
      scientificName: 'Arachis hypogaea',
      genus: 'Arachis',
      species: 'hypogaea',
      author: 'L.',
      commonNames: ['Peanut', 'Amendoim', 'Maní'],
      synonyms: [],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.ANNUAL,
      heightMeters: 0.5,
      canopyWidthMeters: 0.6,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.DECIDUOUS,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.TAPROOT,
      nitrogenFixer: true,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 1,
      uses: [PlantUse.HUMAN_FOOD, PlantUse.ANIMAL_FOOD, PlantUse.OIL],
      propagationMethods: ['Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Nitrogen fixer. Geocarpic - fruits underground.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'perennial-peanut-arachis-pintoi',
      scientificName: 'Arachis pintoi',
      genus: 'Arachis',
      species: 'pintoi',
      author: 'Krapov. & W.C.Greg.',
      commonNames: ['Perennial Peanut', 'Amendoim-forrageiro', 'Pinto peanut'],
      synonyms: [],
      botanicalFamily: 'Fabaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 0.3,
      canopyWidthMeters: 1.0,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TROPICAL_RAINFOREST',
      regionalBiome: ['AMAZON'],
      foliageType: FoliageType.EVERGREEN,
      growthRate: GrowthRate.MEDIUM,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: true,
      biomassProduction: BiomassProduction.MEDIUM,
      hasFruit: true,
      edibleFruit: false,
      uses: [PlantUse.ANIMAL_FOOD, PlantUse.GROUND_COVER],
      propagationMethods: ['Stolons', 'Seeds'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Excellent living mulch. Nitrogen fixer. Suppresses weeds.',
      status: 'PUBLISHED' as const,
    },
    {
      slug: 'strawberry-fragaria-ananassa',
      scientificName: 'Fragaria × ananassa',
      genus: 'Fragaria',
      species: 'ananassa',
      author: 'Duchesne ex Rozier',
      commonNames: ['Strawberry', 'Morango', 'Fresa'],
      synonyms: [],
      botanicalFamily: 'Rosaceae',
      stratum: Stratum.GROUND,
      successionalStage: SuccessionalStage.PIONEER,
      lifeCycle: LifeCycle.PERENNIAL,
      heightMeters: 0.3,
      canopyWidthMeters: 0.5,
      canopyShape: CanopyShape.IRREGULAR,
      originCenter: 'Brazil',
      globalBiome: 'TEMPERATE_FOREST',
      regionalBiome: ['ATLANTIC_FOREST'],
      foliageType: FoliageType.SEMI_EVERGREEN,
      growthRate: GrowthRate.FAST,
      rootSystem: RootSystem.FIBROUS,
      nitrogenFixer: false,
      biomassProduction: BiomassProduction.LOW,
      hasFruit: true,
      edibleFruit: true,
      fruitingAgeStart: 1, fruitingAgeEnd: 1,
      uses: [PlantUse.HUMAN_FOOD],
      propagationMethods: ['Runners', 'Division'],
      germinationDaysMin: 14, germinationDaysMax: 60,
      observations: 'Popular berry. Spreads by stolons. Needs cooler climates.',
      status: 'PUBLISHED' as const,
    },
  ]

  console.log(`\n📦 Creating ${speciesData.length} species...`)

  for (const data of speciesData) {
    // Randomly assign creator from all users
    const creator = allUsers[Math.floor(Math.random() * allUsers.length)]

    const species = await prisma.species.upsert({
      where: { slug: data.slug },
      update: {},
      create: {
        ...data,
        createdById: creator.id,
      },
    })

    // Add a placeholder photo for each species
    const photoUrl = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='600'%3E%3Crect width='800' height='600' fill='%234ade80'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='sans-serif' font-size='24' fill='white'%3E${encodeURIComponent(species.scientificName)}%3C/text%3E%3C/svg%3E`

    await prisma.photo.upsert({
      where: { id: `photo-${species.slug}` },
      update: {},
      create: {
        id: `photo-${species.slug}`,
        url: photoUrl,
        caption: `${species.scientificName}`,
        tags: ['whole'],
        approved: true,
        primary: true,
        speciesId: species.id,
        uploadById: creator.id,
      },
    })

    console.log(`  ✅ ${species.scientificName} (${species.slug})`)
  }

  // Seed badges
  console.log('\n🏅 Creating badges...')

  const badgesData = [
    // Planter badges (syntropic metaphor: planting seeds)
    {
      code: 'FIRST_STEPS',
      name: 'First Seed',
      description: 'Plant your first species in the encyclopedia',
      icon: '🌱',
      category: BadgeCategory.CONTRIBUTOR,
      requirement: { type: 'species_submitted', count: 1 },
      xpReward: 10,
    },
    {
      code: 'PUBLISHED_AUTHOR',
      name: 'Germinated',
      description: 'Your first species has germinated in the encyclopedia',
      icon: '🌿',
      category: BadgeCategory.CONTRIBUTOR,
      requirement: { type: 'species_published', count: 1 },
      xpReward: 25,
    },
    {
      code: 'PROLIFIC_CONTRIBUTOR',
      name: 'Abundant Planter',
      description: 'Have 10 species published',
      icon: '🌳',
      category: BadgeCategory.CONTRIBUTOR,
      requirement: { type: 'species_published', count: 10 },
      xpReward: 100,
    },
    {
      code: 'ENCYCLOPEDIA_BUILDER',
      name: 'Consortium Architect',
      description: 'Have 50 species published - building diverse consortiums',
      icon: '🌲',
      category: BadgeCategory.CONTRIBUTOR,
      requirement: { type: 'species_published', count: 50 },
      xpReward: 500,
    },
    {
      code: 'PHOTOGRAPHER',
      name: 'Light Capturer',
      description: 'Capture the light of 10 species with photos',
      icon: '☀️',
      category: BadgeCategory.CONTRIBUTOR,
      requirement: { type: 'photos_approved', count: 10 },
      xpReward: 25,
    },
    {
      code: 'DETAIL_MASTER',
      name: 'Complete Planting',
      description: 'Submit a species with all optional fields filled',
      icon: '🔍',
      category: BadgeCategory.CONTRIBUTOR,
      requirement: { type: 'complete_species', count: 1 },
      xpReward: 50,
    },

    // Succession Guide badges (syntropic metaphor: pruning guides succession)
    {
      code: 'FIRST_REVIEW',
      name: 'First Pruning',
      description: 'Complete your first review - guiding the succession',
      icon: '✂️',
      category: BadgeCategory.REVIEWER,
      requirement: { type: 'reviews_given', count: 1 },
      xpReward: 10,
    },
    {
      code: 'QUALITY_GUARDIAN',
      name: 'Succession Guardian',
      description: 'Complete 10 reviews - protecting the succession',
      icon: '🛡️',
      category: BadgeCategory.REVIEWER,
      requirement: { type: 'reviews_given', count: 10 },
      xpReward: 50,
    },
    {
      code: 'SENIOR_REVIEWER',
      name: 'Master Pruner',
      description: 'Complete 50 reviews - mastering the art of pruning',
      icon: '⭐',
      category: BadgeCategory.REVIEWER,
      requirement: { type: 'reviews_given', count: 50 },
      xpReward: 200,
    },
    {
      code: 'MASTER_CURATOR',
      name: 'Ecosystem Curator',
      description: 'Complete 100 reviews - curating the ecosystem',
      icon: '👑',
      category: BadgeCategory.REVIEWER,
      requirement: { type: 'reviews_given', count: 100 },
      xpReward: 500,
    },
    {
      code: 'SHARP_EYE',
      name: 'Keen Observer',
      description: 'Maintain 90%+ approval accuracy with at least 20 reviews',
      icon: '🎯',
      category: BadgeCategory.REVIEWER,
      requirement: { type: 'approval_accuracy', minReviews: 20, accuracy: 90 },
      xpReward: 100,
    },

    // Community badges
    {
      code: 'VERIFIED_REVIEWER',
      name: 'Verified Guide',
      description: 'Become a verified succession guide',
      icon: '✓',
      category: BadgeCategory.COMMUNITY,
      requirement: { type: 'role', role: 'REVIEWER' },
      xpReward: 25,
    },
    {
      code: 'EARLY_ADOPTER',
      name: 'Pioneer',
      description: 'Join Syntropedia in the pioneer days',
      icon: '🚀',
      category: BadgeCategory.SPECIAL,
      requirement: { type: 'joined_before', date: '2025-12-31' },
      xpReward: 50,
    },
    {
      code: 'STREAK_7',
      name: 'Weekly Rhythm',
      description: 'Be active 7 days in a row - finding your natural rhythm',
      icon: '🔥',
      category: BadgeCategory.COMMUNITY,
      requirement: { type: 'streak', days: 7 },
      xpReward: 25,
    },
    {
      code: 'STREAK_30',
      name: 'Monthly Cycle',
      description: 'Be active 30 days in a row - completing a full cycle',
      icon: '💫',
      category: BadgeCategory.COMMUNITY,
      requirement: { type: 'streak', days: 30 },
      xpReward: 100,
    },
  ]

  for (const badge of badgesData) {
    await prisma.badge.upsert({
      where: { code: badge.code },
      update: badge,
      create: badge,
    })
    console.log(`  ✅ ${badge.name} (${badge.code})`)
  }

  // Assign badges to users
  console.log('\n🎖️ Assigning badges to users...')

  // Helper function to award badge to user
  async function awardBadge(userEmail: string, badgeCode: string) {
    const user = await prisma.user.findUnique({ where: { email: userEmail } })
    const badge = await prisma.badge.findUnique({ where: { code: badgeCode } })
    if (user && badge) {
      await prisma.userBadge.upsert({
        where: { userId_badgeId: { userId: user.id, badgeId: badge.id } },
        update: {},
        create: { userId: user.id, badgeId: badge.id },
      })
    }
  }

  // Admin - lots of badges (Horticulturist level 7)
  await awardBadge('admin@syntropedia.org', 'FIRST_STEPS')
  await awardBadge('admin@syntropedia.org', 'PUBLISHED_AUTHOR')
  await awardBadge('admin@syntropedia.org', 'PROLIFIC_CONTRIBUTOR')
  await awardBadge('admin@syntropedia.org', 'PHOTOGRAPHER')
  await awardBadge('admin@syntropedia.org', 'FIRST_REVIEW')
  await awardBadge('admin@syntropedia.org', 'QUALITY_GUARDIAN')
  await awardBadge('admin@syntropedia.org', 'SENIOR_REVIEWER')
  await awardBadge('admin@syntropedia.org', 'VERIFIED_REVIEWER')
  await awardBadge('admin@syntropedia.org', 'EARLY_ADOPTER')
  console.log('  ✅ Admin badges assigned')

  // Maria Silva - Green Thumb level 4
  await awardBadge('maria.silva@syntropedia.org', 'FIRST_STEPS')
  await awardBadge('maria.silva@syntropedia.org', 'PUBLISHED_AUTHOR')
  await awardBadge('maria.silva@syntropedia.org', 'PROLIFIC_CONTRIBUTOR')
  await awardBadge('maria.silva@syntropedia.org', 'PHOTOGRAPHER')
  await awardBadge('maria.silva@syntropedia.org', 'EARLY_ADOPTER')
  console.log('  ✅ Maria Silva badges assigned')

  // João Santos - Sapling level 3
  await awardBadge('joao.santos@syntropedia.org', 'FIRST_STEPS')
  await awardBadge('joao.santos@syntropedia.org', 'PUBLISHED_AUTHOR')
  await awardBadge('joao.santos@syntropedia.org', 'EARLY_ADOPTER')
  console.log('  ✅ João Santos badges assigned')

  // Dr. Ana Botânica - Botanist level 8 (top reviewer)
  await awardBadge('dr.botanica@syntropedia.org', 'FIRST_STEPS')
  await awardBadge('dr.botanica@syntropedia.org', 'PUBLISHED_AUTHOR')
  await awardBadge('dr.botanica@syntropedia.org', 'PROLIFIC_CONTRIBUTOR')
  await awardBadge('dr.botanica@syntropedia.org', 'PHOTOGRAPHER')
  await awardBadge('dr.botanica@syntropedia.org', 'DETAIL_MASTER')
  await awardBadge('dr.botanica@syntropedia.org', 'FIRST_REVIEW')
  await awardBadge('dr.botanica@syntropedia.org', 'QUALITY_GUARDIAN')
  await awardBadge('dr.botanica@syntropedia.org', 'SENIOR_REVIEWER')
  await awardBadge('dr.botanica@syntropedia.org', 'MASTER_CURATOR')
  await awardBadge('dr.botanica@syntropedia.org', 'SHARP_EYE')
  await awardBadge('dr.botanica@syntropedia.org', 'VERIFIED_REVIEWER')
  await awardBadge('dr.botanica@syntropedia.org', 'EARLY_ADOPTER')
  await awardBadge('dr.botanica@syntropedia.org', 'STREAK_7')
  console.log('  ✅ Dr. Ana Botânica badges assigned')

  // Prof. Carlos - Gardener level 6
  await awardBadge('prof.agroforestry@syntropedia.org', 'FIRST_STEPS')
  await awardBadge('prof.agroforestry@syntropedia.org', 'PUBLISHED_AUTHOR')
  await awardBadge('prof.agroforestry@syntropedia.org', 'PROLIFIC_CONTRIBUTOR')
  await awardBadge('prof.agroforestry@syntropedia.org', 'FIRST_REVIEW')
  await awardBadge('prof.agroforestry@syntropedia.org', 'QUALITY_GUARDIAN')
  await awardBadge('prof.agroforestry@syntropedia.org', 'SENIOR_REVIEWER')
  await awardBadge('prof.agroforestry@syntropedia.org', 'VERIFIED_REVIEWER')
  await awardBadge('prof.agroforestry@syntropedia.org', 'EARLY_ADOPTER')
  console.log('  ✅ Prof. Carlos badges assigned')

  // Dra. Fernanda - Cultivator level 5
  await awardBadge('researcher.ecology@syntropedia.org', 'FIRST_STEPS')
  await awardBadge('researcher.ecology@syntropedia.org', 'PUBLISHED_AUTHOR')
  await awardBadge('researcher.ecology@syntropedia.org', 'FIRST_REVIEW')
  await awardBadge('researcher.ecology@syntropedia.org', 'QUALITY_GUARDIAN')
  await awardBadge('researcher.ecology@syntropedia.org', 'VERIFIED_REVIEWER')
  await awardBadge('researcher.ecology@syntropedia.org', 'EARLY_ADOPTER')
  console.log('  ✅ Dra. Fernanda badges assigned')

  console.log('\n🎉 Seed completed successfully!')
  console.log(`\n📊 Summary:`)
  console.log(`   Users: ${await prisma.user.count()}`)
  console.log(`   Species: ${await prisma.species.count()}`)
  console.log(`   Photos: ${await prisma.photo.count()}`)
  console.log(`   Badges: ${await prisma.badge.count()}`)
  console.log(`   User Badges: ${await prisma.userBadge.count()}`)
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
